name: Main workflow
on: 
  push:
    branches: [ main ]
jobs:
  run:
    name: Run
    using: 'docker'
    image: 'electronuserland/builder:wine'
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: npm ci
        run: npm ci
      - name: Dist
        run: npm run-script dist
